### ISSUE TITLE
Paginas web de referencia - Hospital

### ISSUE THREAD

**Issue by storres20** [Ismis-Future/WebHospital#4]
## Detalle:
* Buscar algunas paginas webs que les guste para usarlas como referencia para hacer el diseño en Figma

**Comment by Ismis-Future** [comment]
https://www.iess.gob.ec/

**Comment by storres20** [comment]
## Paginas web de referencia:
* http://www.insnsb.gob.pe/ (se usará de referencia para el presente proyecto)
* https://www.inmp.gob.pe/

**Comment by storres20** [comment]
## Atendido
