### ISSUE TITLE
Image Slider Animation - Figma

### ISSUE THREAD

**Issue by storres20** [Ismis-Future/WebHospital#8]
## Detalle:
* Elaborar el Image Slider Animation

**Comment by storres20** [comment]
## Avances en Figma:
* Image Slider Animation
![image](https://user-images.githubusercontent.com/81504385/154833571-07793cd6-30b1-41df-968c-d66c961d7c50.png)

* Para ver la animacion del Slider, dar click en el boton "present"
![image](https://user-images.githubusercontent.com/81504385/154833648-03f1d951-6431-47b3-965e-c7d278915643.png)

* Luego dar click en la flecha "<" o ">" para cambiar de Slide

**Comment by Ismis-Future** [comment]
color para el fondo del slider: #7BE9FF

**Comment by storres20** [comment]
## Atendido
